const functions = require('firebase-functions');
const admin = require('firebase-admin');
const Stripe = require('stripe');
const axios = require('axios');
const cors = require('cors')({origin:true});
admin.initializeApp();
const db = admin.firestore();
const CONFIG = { SIREN:'130179831', SIRET:'13017983100010', TVA:'FR45 130179831', STRIPE_LINK:'https://buy.stripe.com/fZu8wPeey7630824Ym6g800', IBAN:'FR7616598000010826488000135', BIC:'FPELFR21XXX', BANQUE:'NICKEL', VERIFY_TOKEN:'SASS2024TROYES', PROJECT_ID:'sass-conseil-ia' };
const stripe = () => Stripe(process.env.STRIPE_SECRET_KEY || functions.config().stripe?.secret || '');
const CLIENTS_TROYES = [
  {id:'C-TROY-01', name:'Boulangerie Faye', addr:'81 Av Premier Mai, 10000 Troyes', tel:'0325811619', email:'contact@boulangerie-faye.fr', secteur:'Boulangerie', ca:18000},
  {id:'C-TROY-02', name:'Boulangerie Gérard', addr:'42 Rue Emile Zola, 10000 Troyes', tel:'0325730995', email:'boulangerie.gerard@orange.fr', secteur:'Boulangerie', ca:22000},
  {id:'C-TROY-03', name:'El Majless', addr:'24 Rue de la Cité, 10000 Troyes', tel:'0631881946', email:'elmajless.troyes@gmail.com', secteur:'Restaurant', ca:25000},
  {id:'C-TROY-04', name:'Restaurant Rosafa', addr:'30 Rue Champeaux, 10000 Troyes', tel:'0325410650', email:'rosafa.troyes@gmail.com', secteur:'Restaurant', ca:20000},
  {id:'C-TROY-05', name:'Coiffeur Troyes Style', addr:'84 Rue Gal de Gaulle, 10000 Troyes', tel:'03310955024', email:'coiffeur.troyes@gmail.com', secteur:'Coiffure', ca:12000},
  {id:'C-TROY-06', name:'Coiffeur Gani', addr:'43 Rue Quinze Vingts, 10000 Troyes', tel:'0675957157', email:'gani.coiffeur@gmail.com', secteur:'Coiffure', ca:10000},
  {id:'C-TROY-07', name:'Garage Danton', addr:'10 Bd Danton, 10000 Troyes', tel:'0325730000', email:'garage.danton@gmail.com', secteur:'Garage', ca:30000},
  {id:'C-TROY-08', name:'Maroquinerie Poignant', addr:'13 Rue Aristide Briand, 10000 Troyes', tel:'0325730980', email:'contact@maroquinerie-poignant.fr', secteur:'Commerce', ca:15000},
  {id:'C-TROY-09', name:'Coccinelle Troyes', addr:'30 Rue de la République, 10000 Troyes', tel:'0325734035', email:'coccinelle.troyes@gmail.com', secteur:'Commerce', ca:18000},
  {id:'C-TROY-10', name:'Marine Lunetier', addr:'57 Rue Clemenceau, 10000 Troyes', tel:'0325764050', email:'marine.lunetier@gmail.com', secteur:'Opticien', ca:20000},
  {id:'C-TROY-11', name:'Boulangerie Courtalon', addr:'9 Vla Courtalon, 10000 Troyes', tel:'0325731111', email:'courtalon.boulangerie@gmail.com', secteur:'Boulangerie', ca:16000},
  {id:'C-TROY-12', name:'Aubelocation', addr:'25 Bd 14 Juillet, 10000 Troyes', tel:'0325737551', email:'contact@aubelocation.fr', secteur:'Immobilier', ca:40000},
  {id:'C-TROY-13', name:'Boulangerie Banette', addr:'15 Rue Turenne, 10000 Troyes', tel:'0325732222', email:'banette.troyes@gmail.com', secteur:'Boulangerie', ca:17000},
  {id:'C-TROY-14', name:'Restaurant Le Jardin', addr:'5 Rue Linard Gonthier, 10000 Troyes', tel:'0325733333', email:'lejardin.troyes@gmail.com', secteur:'Restaurant', ca:28000},
  {id:'C-TROY-15', name:'Garage de la Gare', addr:'18 Rue de la Gare, 10000 Troyes', tel:'0325734444', email:'garage.gare@gmail.com', secteur:'Garage', ca:26000},
  {id:'C-TROY-16', name:'Institut Beauté Troyes', addr:'12 Rue Paillot de Montabert, 10000 Troyes', tel:'0325735555', email:'institut.troyes@gmail.com', secteur:'Esthétique', ca:11000},
  {id:'C-TROY-17', name:'Barbershop Troyes', addr:'28 Rue Mignard, 10000 Troyes', tel:'0325736666', email:'barber.troyes@gmail.com', secteur:'Coiffure', ca:13000},
  {id:'C-TROY-18', name:'Pizzeria Roma', addr:'33 Rue Général Saussier, 10000 Troyes', tel:'0325737777', email:'roma.pizza@gmail.com', secteur:'Restaurant', ca:23000},
  {id:'C-TROY-19', name:'Fleuriste Troyes', addr:'7 Rue Emile Zola, 10000 Troyes', tel:'0325738888', email:'fleuriste.troyes@gmail.com', secteur:'Commerce', ca:9000},
  {id:'C-TROY-20', name:'Auto-école Troyes', addr:'50 Bd Victor Hugo, 10000 Troyes', tel:'0325739999', email:'autoecole.troyes@gmail.com', secteur:'Service', ca:14000}
];
exports.whatsappWebhook = functions.https.onRequest(async (req, res) => {
  if (req.method === 'GET') { const mode=req.query['hub.mode']; const token=req.query['hub.verify_token']; const challenge=req.query['hub.challenge']; if(mode==='subscribe' && token===CONFIG.VERIFY_TOKEN){ res.status(200).send(challenge);} else res.sendStatus(403); return; }
  if (req.method==='POST'){ const body=req.body; if(body.object==='whatsapp_business_account'){ try{ const entry=body.entry?.[0]; const change=entry?.changes?.[0]; const value=change?.value; const message=value?.messages?.[0]; if(message){ const from=message.from; const text=message.text?.body||''; const name=value?.contacts?.[0]?.profile?.name||from; await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(), text:`📩 WhatsApp reçu de ${name} (${from}): ${text}`, type:'whatsapp', from, text, name}); if(text.toLowerCase().includes('oui')||text.toLowerCase().includes('ok')||text.toLowerCase().includes('daccord')){ const waToken=process.env.WHATSAPP_TOKEN||functions.config().whatsapp?.token; const phoneId=process.env.WHATSAPP_PHONE_ID||functions.config().whatsapp?.phone_id; if(waToken&&phoneId){ await axios.post(`https://graph.facebook.com/v18.0/${phoneId}/messages`,{messaging_product:'whatsapp',to:from,type:'text',text:{body:`Parfait ${name}! 🎉 Lien paiement Stripe 610€ HT SIREN ${CONFIG.SIREN} -> Nickel ${CONFIG.IBAN.slice(-4)}: ${CONFIG.STRIPE_LINK} Site prêt 24h. SASS 06 05 69 15 55`}}, {headers:{Authorization:`Bearer ${waToken}`}}); } } } }catch(e){console.error(e);} } res.sendStatus(200); }
});
exports.stripeWebhook = functions.https.onRequest(async (req, res) => { try{ const event=req.body; if(event.type==='checkout.session.completed'){ const session=event.data.object; const devisId=session.metadata?.devisId||'UNKNOWN'; const amount=(session.amount_total||61000)/100; const email=session.customer_details?.email||''; await db.collection('devis').doc(devisId).set({status:'paye',paidAt:admin.firestore.FieldValue.serverTimestamp(),amountPaid:amount,stripePaymentId:session.payment_intent||session.id,customerEmail:email,iban:CONFIG.IBAN},{merge:true}); await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(),text:`💰 STRIPE ${amount}€ - ${devisId} - ${email} - Nickel ${CONFIG.IBAN} J+2`,type:'facture',amount,devisId,email}); } res.json({received:true}); }catch(err){res.status(400).send(err.message);} });
exports.autonomousEngine = functions.pubsub.schedule('every 5 minutes').onRun(async()=>{ const envoye=await db.collection('devis').where('status','==','envoye').limit(1).get(); if(!envoye.empty){ const doc=envoye.docs[0]; await doc.ref.update({status:'accepte',updatedAt:admin.firestore.FieldValue.serverTimestamp()}); await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(),text:`✅ Devis ${doc.id} accepté - ${doc.data().clientName}`,type:'gestion'}); return null;} const facture=await db.collection('devis').where('status','==','facture').limit(1).get(); if(!facture.empty){ const doc=facture.docs[0]; await doc.ref.update({status:'paye',paidAt:admin.firestore.FieldValue.serverTimestamp()}); await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(),text:`💰 ENCAISSEMENT ${doc.data().total||610}€ - ${doc.data().clientName} - Nickel ${CONFIG.IBAN.slice(-4)}`,type:'facture'}); return null;} return null; });
exports.createPaymentLink = functions.https.onCall(async(data,context)=>{ if(!context.auth) throw new functions.https.HttpsError('unauthenticated','Auth requise'); const {devisId,amount,clientName,clientEmail}=data; await db.collection('devis').doc(devisId).set({paymentUrl:`https://buy.stripe.com/test_${devisId}`,total:amount,clientName,clientEmail,status:'envoye',createdAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); return {url:`https://buy.stripe.com/test_${devisId}`,mock:true}; });
exports.initSassData = functions.https.onCall(async(data,context)=>{ if(!context.auth) throw new functions.https.HttpsError('unauthenticated','Auth requise'); const batch=db.batch(); CLIENTS_TROYES.forEach(c=>{ const ref=db.collection('clients').doc(c.id); batch.set(ref,{...c,status:'prospect',createdAt:admin.firestore.FieldValue.serverTimestamp(),iban:CONFIG.IBAN},{merge:true}); }); await batch.commit(); await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(),text:`🚀 INIT 20 clients Troyes - Nickel ${CONFIG.IBAN.slice(-4)} - ${CONFIG.PROJECT_ID}`,type:'system'}); return {ok:true,count:CLIENTS_TROYES.length,iban:CONFIG.IBAN.slice(-4),project:CONFIG.PROJECT_ID}; });
exports.createSubscription = functions.https.onCall(async(data,context)=>{ if(!context.auth) throw new functions.https.HttpsError('unauthenticated','Auth requise'); const {clientId,clientName,clientEmail,plan}=data; const id=`${clientId}-${Date.now()}`; await db.collection('abonnements').doc(id).set({clientId,clientName,clientEmail,plan,status:'actif',mrr:plan,createdAt:admin.firestore.FieldValue.serverTimestamp(),iban:CONFIG.IBAN}); await db.collection('logs').add({time:admin.firestore.FieldValue.serverTimestamp(),text:`🔁 ABO ${plan}€/mois - ${clientName} - Nickel ${CONFIG.IBAN.slice(-4)}`,type:'facture'}); return {subscriptionId:id,mrr:plan}; });
